apiVersion: cpln.io/v1
kind: gvc
metadata:
  name: {{ .Values.gvc }}
  namespace: {{ .Release.Namespace }}
org: {{ .Values.org }}
description: {{ .Values.gvc }}
tags: {}
spec:
  staticPlacement:
    locationLinks:
      - //location/aws-eu-central-1
