apiVersion: cpln.io/v1
kind: workload
metadata:
  name: hello-world
  namespace: {{ .Release.Namespace }}
org: {{ .Values.org }}
gvc: {{ .Values.gvc }}
description: hello-world
tags: {}
spec:
  type: standard
  containers:
    - name: hello-world
      cpu: 50m
      env: []
      image: //image/hello-world:v1
      inheritEnv: false
      memory: 128Mi
      ports:
        - number: 3000
          protocol: http
      volumes: []
  defaultOptions:
    autoscaling:
      maxConcurrency: 0
      maxScale: 1
      metric: disabled
      minScale: 1
      scaleToZeroDelay: 300
      target: 95
    capacityAI: true
    debug: false
    suspend: false
    timeoutSeconds: 5
  firewallConfig:
    external:
      inboundAllowCIDR:
        - 0.0.0.0/0
      inboundBlockedCIDR: []
      outboundAllowCIDR: []
      outboundAllowHostname: []
      outboundAllowPort: []
      outboundBlockedCIDR: []
    internal:
      inboundAllowType: none
      inboundAllowWorkload: []
  loadBalancer:
    replicaDirect: false
  localOptions: []
  supportDynamicTags: false
